### PR TITLE
servo: fix evaluation on unstable/18.09

### LINKED ISSUE #110: nixpkgs-mozilla does not evaluate on unstable and 18.09
```
$ nix-env -f package-set.nix -qa '*' --meta --xml --drv-path --show-trace --arg pkgs "import <nixpkgs> {}" >/dev/null
error: while querying the derivation named 'servo-latest':
while evaluating the attribute 'buildInputs' of the derivation 'servo-latest' at /home/joerg/git/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:179:11:
while evaluating 'getOutput' at /home/joerg/git/nixpkgs/lib/attrsets.nix:452:23, called from undefined position:
while evaluating anonymous function at /home/joerg/git/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:127:17, called from undefined position:
attribute 'mesa' missing, at /home/joerg/git/nixpkgs-mozilla/pkgs/servo/default.nix:7:4
```

### PR DESCRIPTION
**Pull request by Mic92**
fixes #110

### CODE REVIEW

**Comment by Mic92** [comment]
This blocks https://github.com/nix-community/NUR/pull/77

**Comment by Mic92** [comment]
Anything blocking this?

**Comment by zimbatm** [comment]
@garbas @nbp mind merging this? I lost access on this repo

**Comment by nbp** [comment]
Trying with nix-instantiate, I have the same error with:

```nix
let x = {}; in let inherit (x) mesa; in (mesa ? null)
```

The `?` operator will return `true` or `false` whether the attribute `null` exists in `mesa`. I guess you meant something like `pkgs.mesa or null` ?

**Comment by Mic92** [comment]
Weird. I thought I tested this.

**Comment by Mic92** [comment]
This pull request will be obsolete when this one is merged: https://github.com/mozilla/nixpkgs-mozilla/pull/114

**Comment by Mic92** [comment]
obsolete now

**Pull request closed without merging**
