### PR TITLE
README: usage example

### PR DESCRIPTION
**Pull request by veprbl**
Fixes: #73

### CODE REVIEW

**Comment by zimbatm** [comment]
1.11 is also supposed to work. /cc @nbp

**Comment by veprbl** [comment]
@zimbatm Evaluation is only broken on macOS + nix 1.11. I think it's a known bug in stable nix, so I'm dropping that part from my PR. 

For the reference, the error looks like:
```
error: compiling pattern ‘([
]*(=|[[][[][a-zA-Z0-9_."*-]+[]][]]|[[][a-zA-Z0-9_."*-]+[]]|[a-zA-Z0-9_-]+|"[^"]*")[
]+(=|[[][[][a-zA-Z0-9_."*-]+[]][]]|[[][a-zA-Z0-9_."*-]+[]]|[a-zA-Z0-9_-]+|"[^"]*")[
]+(=|[[][[][a-zA-Z0-9_."*-]+[]][]]|[[][a-zA-Z0-9_."*-]+[]]|[a-zA-Z0-9_-]+|"[^"]*")[
<snip>
```

**Comment by zimbatm** [comment]
I see. I think that Nix is depending on std::regex which implementation might differ between c++ stdlib implementations.

**Comment by nbp** [comment]
This is a known bug, which has easy known work-around as mentioned in other issues (https://github.com/mozilla/nixpkgs-mozilla/issues/33#issuecomment-301837715). The error reporting is a Mac issue, but the issue is an out-of-memory issue, where for parsing we need more than available on the system.

**Comment by nbp** [comment]
Also, I forgot the essential, …
Thanks for adding these notes to the README. :)

**Pull request merged**
