### PR TITLE
VidyoDesktop requires libGL on unstable

### PR DESCRIPTION
**Pull request by glasserc**
Thanks to @washort for telling me how to get it running again.

### CODE REVIEW

**Comment by bkchr** [comment]
For me also `libidn.so.11` is missing?

**Comment by garbas** [comment]
@bkchr did you manage to find out how to fix missing ``libidn.so.11``?

**Comment by garbas** [comment]
i mean i see `libidn` package added to the multiPkgs list, but still doesn't find the library

**Comment by garbas** [comment]
aha looks like libidn is too new

**Comment by bkchr** [comment]
Yep, did you see my pr?

**Comment by garbas** [comment]
going to downgrade to libidn-1.34

**Comment by garbas** [comment]
fixed in https://github.com/mozilla/nixpkgs-mozilla/commit/64e9d5c45e228bfb963f197b5f025d6f607d51ae

**Comment by bkchr** [comment]
@garbas why not merge my commit? https://github.com/mozilla/nixpkgs-mozilla/pull/101

**Comment by garbas** [comment]
@bkchr I'm sorry. I'm mad at myself to do more work then needed.

**Comment by bkchr** [comment]
@garbas yeah np ;)

**Pull request merged**
