### PR TITLE
Remove obsolete warning

### PR DESCRIPTION
**Pull request by lheckemann**
That release is now the current one :)

### CODE REVIEW

**Comment by zimbatm** [comment]
Maybe we can keep the warning to say it starts working from 17.03?

**Comment by garbas** [comment]
I think we could / should check this in nix and warn if it nixpkgs is not compatible

**Comment by zimbatm** [comment]
How can we do that? The failure scenario here is that if nixpkgs doesn't support it, the symlink will be ignored.

**Comment by lheckemann** [comment]
Since 17.03 is the current stable release and 16.09 support is ending in 4 days, perhaps merge this as-is then?

**Comment by garbas** [comment]
https://github.com/NixOS/nixpkgs/blob/master/lib/trivial.nix#L137

**Comment by lheckemann** [comment]
> we can fetch nixpkgs version using pkgs.lib.nixpkgsVersion and then use builtins.abort "You need to use nixpkgs>=17.03"

No, because at no point will any expressions from nixpkgs-mozilla be evaluated if the nixpkgs version doesn't support overlays...

**Comment by lheckemann** [comment]
Since removing the warning completely seems to be an unpopular option, I've rephrased it instead.

**Pull request merged**
