### PR TITLE
initial flake support

### PR DESCRIPTION
**Pull request by nrdxp**
This pr introduces initial [flake](https://github.com/tweag/rfcs/blob/flakes/rfcs/0049-flakes.md) support. I'm opening as a draft since flakes are not yet merged and subject to change. Not everything works just yet, since `fetchurl` must provide a checksum in flakes. Could use some help exploring possible solutions. 

Since the manifest files get updated on a fairly frequent basis, I was thinking maybe a simple shell script that runs `nix-prefect-git` on their urls and stores the sums in a local json file, which then gets pulled in to the overlays. Since this might cause a lot of commits every time they change, maybe there is a simpler way. I've tried supplying their sha256 sums manually just to ensure everything works, and it does.

### CODE REVIEW

**Comment by glasserc** [comment]
Hmm! I'm not an expert (I'm not even 100% sure I understand how flakes work) but since nobody has looked at this so far, I'll give it a shot. It does seem like a challenge that there's no way to express a dependency on a URL, but I guess it's by definition impure. I agree that moving to committing the checksums for each build is a valid approach -- there's some precedent I guess, for example there's https://github.com/NixOS/nixpkgs/blob/a27aa247c0681252f923fc0f39059e01a303dece/pkgs/development/mobile/androidenv/generate.sh. On the other hand I would prefer not to have those commits cluttering up this repository. Maybe we could make a separate repository with just Nix-formatted checksums? Seems a little overkill..

Is the change of `self: super:` to `final: prev:` also part of the move to flakes? It might be better to extract that as a separate change, to make things easier to review.

**Comment by nrdxp** [comment]
yes `final: prev:` is part of the new ui, although not strictly required, it does throw an error when running `nix flake check`. I could definitely extract it out. I am wondering if it might be easier to request an addition to the flakes concept a la flake arguments. This would allow to pass the checksum to the flake via the users personal flake. I'll bounce this off upstream and see what they think.

**Comment by petabyteboy** [comment]
You can always return a function that the user has to call with the hashes.

**Comment by garbas** [comment]
I would only open a PR with only adding flake support. and avoid having to many changes in one PR. Also you could  use flake-compat, to [provide compatibility](https://github.com/NixOS/nixos-homepage/blob/master/default.nix) with Nix versions that don't support flakes

**Comment by bqv** [comment]
@nrdxp why did you close?

**Comment by nrdxp** [comment]
Not enough time to work out the kinks unfortunately.

**Pull request closed without merging**
