### PR TITLE
Add derivation for phlay

### PR DESCRIPTION
**Pull request by glasserc**

### CODE REVIEW

**Comment by glasserc** [comment]
Once #122 lands, it would probably be good to add a section about "Submitting patches", which can describe the current options (`arcanist`, `moz-phab`, and this).

**Comment by garbas** [comment]
@glasserc this doesn't look like a mozilla specific package, maybe it would be better to submit it to github.com/nixos/nixpkgs

**Comment by glasserc** [comment]
The second sentence in the project's README begins "Phlay is a hacky tool for people using git for their Mozilla development". I don't think it's appropriate for upstream nixpkgs.

**Comment by garbas** [comment]
@glasserc sorry for my ignorance, your right

**Pull request merged**
