### PR TITLE
Replacing lib/parseTOML with toml2nix

### PR DESCRIPTION
**Pull request by P-E-Meunier**
fromTOML breaks at random times on my machine, and this happened again today. I'm not sure what causes it, and even though I admired the effort (and elegance) of a 100% Nix parser, I decided to write a replacement in a more suited language (Rust with the Toml crate).

Once NixOS/nixpkgs#53883 is accepted, this PR should end the manifest parsing problems of rust-overlay.nix on all platforms, at least for some time.

### CODE REVIEW

**Comment by P-E-Meunier** [comment]
Just a little heads-up, NixOS/nixpkgs#53883 has been merged, hence this PR can now be merged.

**Comment by Ralith** [comment]
This will break users on nixos stable channels.

**Comment by P-E-Meunier** [comment]
Sure, but not merging it will break users on *all* channels ;-)

**Comment by Ralith** [comment]
Only for nightlies, though, right? In any case, maybe we should rely on [the workaround](https://github.com/mozilla/nixpkgs-mozilla/issues/148#issuecomment-455314172) until 19.03 releases?

**Comment by Mic92** [comment]
The solution could be to backport `toml2nix` to stable also.

**Comment by garbas** [comment]
@nbp this PR is now obsolete with the fixes you just merged, right?

**Comment by nbp** [comment]
@garbas, while the motivation is initially the same, I do not think it is. #150 is a work-around for one case of the TOML language.

However, personally, I do not like the import-from-derivation pattern, as this implies that we depend on a derivation execution to get the result of a derivation.

**Comment by Mic92** [comment]
@nbp we could rely on the new toml builtin and only fallback to the input from derivation method if it is not available.

**Comment by garbas** [comment]
I also do not like import-from-derivation pattern, but maybe if this is only a fallback that could be ok. I guess also having a pure nix as a fallback could be ok. Personally I would do whatever is easier to maintain, but since I'm not maintaining it I will let the maintainer (@nbp) decide.

**Comment by andersk** [comment]
I think this can be closed in favor of #205.

**Comment by Mic92** [comment]
I also like https://github.com/nix-community/fenix

**Comment by nbp** [comment]
as mentioned in https://github.com/mozilla/nixpkgs-mozilla/pull/147#issuecomment-850884615 this can be closed as we are already relying on the builtin, which does not use the import-from-derivation pattern.

**Pull request closed without merging**
