### PR TITLE
rust-overlay: drop `header` function

### PR DESCRIPTION
**Pull request by ncfavier**
It was removed in https://github.com/NixOS/nixpkgs/pull/210993

### CODE REVIEW

**Comment by attente** [comment]
Thanks for the fix, it works well for me. Could the maintainers please merge this?

**Comment by andersk** [comment]
Cc @nbp

**Comment by gilescope** [comment]
That would be great. Without this it's a bit broken.

**Comment by ncfavier** [comment]
@colemickens

**Comment by l3gacyb3ta** [comment]
Yeah, this is breaking my install too.

**Comment by nbp** [comment]
Sorry for the delay.
Thanks for fixing this issue.

**Comment by l3gacyb3ta** [comment]
@nbp thank you so much!

**Pull request merged**
